### ISSUE TITLE
How about line-height being the baseline grid? (Mathematical Web Typography)

### ISSUE THREAD

**Issue by cmpsbl** [jxnblk/blog#37]
I enjoyed reading your article.

What do you think about `line-height` being the baseline and all `margins` and `paddings` being the halves or doubles of that baseline? (Which I assume most web designers practice like [this article](http://zellwk.com/blog/why-vertical-rhythms/)).

For example, I'm working on a website, and thinking the typeface looks good in `font-size` of `0.9375rem(15px)` and `line-height` of `1.59375rem(25.5px)`. I understood the power of two, so treid doubling and halving that computed value of `line-height` to get spacing values, but like you said, I started "dealing with less-than-ideal numbers and complex calculations".

You [suggested](http://jxnblk.com/writing/posts/mathematical-web-typography/#1-rem-as-a-base-unit):

> ...setting body copy to `1.125rem (18px)` and keeping other UI elements tied to the base `1rem` can make spacing and alignment adjustments much simpler and help create a natural rhythm in the visual design.

So my question is:
- When you do your work, do you set baseline based on computed value of `line height` and use that baseline for `paddings` and `margins`? (in my case, spacing between elements would be either `6.375px`, `13.25px`, `25.5px`, etc.)
- If your typeface looks good in `15/25.5px`, how would you approach it?

**Comment by cmpsbl** [comment]
Here's  what I currently come up with:

``` css
:root {
  --paragraph-size: 0.9375rem; /* setting body copy to something other than 1rem */
  --base-unit: 1rem; /* like you suggested, UI elements tied to the base 1rem */

  /* for margins, paddings, gutters, etc. */
  --spacing-1: calc(var(--base-unit) * 0.625); 
  --spacing-2: calc(var(--base-unit) * 0.875); 
  --spacing-3: calc(var(--base-unit) * 1.125);  
  --spacing-4: calc(var(--base-unit) * 1.625); /* 26px, this becomes line-height for body copy */
  --spacing-5: calc(var(--base-unit) * 2.125);
  --spacing-6: calc(var(--base-unit) * 3.125);
  --spacing-7: calc(var(--base-unit) * 4.125);

  ...
}
```

Is this configuration following your suggestions correctly? It's not doubling or halving the line-height to get margin and padding values, but it has [1rem as a base unit](http://jxnblk.com/writing/posts/mathematical-web-typography/#1-rem-as-a-base-unit). Or am I completely wrong and should stick to only one ratio to enforce [the power of two denominator](http://jxnblk.com/writing/posts/mathematical-web-typography/#modular-scales-and-factors)? (like basscss's margin and padding declarations ? 0.5, 1, 2, 4, 8...)
